---

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
    - vars/php.yml
    - vars/nginx.yml
    - vars/mysql.yml

  roles:

    - role: geerlingguy.php
    - role: geerlingguy.nginx
    - role: geerlingguy.mysql

  tasks:

    - name: Run setup.sh
      shell: ./setup.sh
      args:
        chdir: /var/www/varena2/scripts/
        executable: /bin/bash

    - name: Copy varena2.conf
      copy: src=./files/varena2.cfg dest=/var/www/varena2/varena2.conf owner=www-data group=www-data mode=0644
