nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80 default_server"
    server_name: "varena2"
    root: "/var/www/varena2/www"
    index: "index.php index.html index.htm"
    extra_parameters: |
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
