nginx_sendfile: "off"
nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80 default_server"
    server_name: "varena"
    root: "/var/www/varena/www"
    index: "index.php index.html index.htm"
    extra_parameters: |
      location /file {
        rewrite ^/file/([^/]+)/([^/]+)$ /file.php?problemName=$1&fileName=$2 break;
      }
      location / {
        if ($request_uri ~ "(/[-a-zA-Z]+)(\?.+$|$)"){
          rewrite (.*)$ /$1.php$2 last;
        }
      }
      location ~ \.php$ {
        if (!-e $document_root$document_uri){
          return 404;
        }
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
