php_enable_webserver: true
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_display_errors: "On"
php_fpm_listen: /run/php/php7.0-fpm.sock
php_packages:
  - php7.0
  - php7.0-cli
  - php7.0-common
  - php7.0-fpm
  - php7.0-mysql
  - php7.0-cgi
php_conf_paths:
  - /etc/php/7.0/fpm
  - /etc/php/7.0/cli
php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/cli/conf.d
php_fpm_daemon: php7.0-fpm
php_fpm_conf_path: "/etc/php/7.0/fpm"
php_fpm_pool_conf_path: "{{ php_fpm_conf_path }}/pool.d/www.conf"
