php_enable_webserver: true
php_webserver_daemon: "nginx"
php_enable_fpm: true
php_packages:
  - php7.0
  - php7.0-cli
  - php7.0-common
  - php7.0-fpm
  - php7.0-mysql
  - php7.0-cgi
php_conf_paths:
  - /etc/php/7.0/fpm
  - /etc/php/7.0/cli
php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/cli/conf.d
php_fpm_daemon: php-fpm7.0
php_fpm_conf_path: "/etc/php/7.0/fpm"
